### ISSUE TITLE
Array.Resize() to remove elements removing too many [7:37am]

### ISSUE THREAD

**Issue by alloursjournall** [frankcollins3/fcc-mcsft-cSharp#25]
**attempting to do:**
Array.Resize() and then index reassignment to add values to array [x]
Array.Resize() to resize the array to a smaller Length and remove array-items

![Screen Shot 2023-09-09 at 7 38 28 AM](https://github.com/frankcollins3/fcc-mcsft-cSharp/assets/73137934/21588523-7689-4752-936d-7e1fb302efaf)

**error:**
as can be seen above the third item during the second rendering of showPallets() data:
```
second showpallets
check:
 check:
 check:
 check: 	 A13
 check: 	 C01
 check: 	 C02
 check: 	 C40
```
![Screen Shot 2023-09-09 at 7 37 01 AM](https://github.com/frankcollins3/fcc-mcsft-cSharp/assets/73137934/89d9d6a0-10d6-479c-ab9d-2663e80051a7)

**proposed approach:**
👍 Array.Resize(ref pallets, 4);
 Resizing 3 ... count: 	 4
check:
 check:
 check:
 check: 	 A13

**possible improvements:**
read the code better. this is a human error issue. wasn't seeing the third check.
